// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package hive_service

import (
	"bytes"
	"github.com/ralphal/hive/thriftlib/fb303"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"github.com/ralphal/hive/thriftlib/hive_metastore"
	"github.com/ralphal/hive/thriftlib/queryplan"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = fb303.GoUnusedProtection__
var _ = hive_metastore.GoUnusedProtection__
var _ = queryplan.GoUnusedProtection__

func init() {
}
