// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package serde

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

type PrimitiveType string

func PrimitiveTypePtr(v PrimitiveType) *PrimitiveType { return &v }

type CollectionType string

func CollectionTypePtr(v CollectionType) *CollectionType { return &v }

